### PR TITLE
Routing & Configuration 2

### PR DESCRIPTION
**Pull request by hnrchrdl**
So now, we have no automatic merge anymore, not sure if i did everything right with rebasing and merging the remote stuff.
Thanks for your help. And sorry for abusing your project to learn to contribute to open source.

### CODE REVIEW

**Comment by stuartkuentzel** [comment]
I merged your stuff in again, but had to resolve a conflict and commit on your branch. I'm hoping this time you'll get credit for your work. It looks like a lot of the stuff from your initial commit was missing though. So we can try this again if you're up for it.

**Comment by hnrchrdl** [comment]
Weird that the stuff from the first PR is missing, because in my fork it is actually there. Must have something to do with the reverting, I guess.
I do not really mind the credits, by the way. More interested in learning how this stuff works.

**Comment by stuartkuentzel** [comment]
I just reverted everything to your original pull request. It looks like your work is there. I'm also trying to navigate my way through this, so thanks for the patience.

**Comment by stuartkuentzel** [comment]
Also, found this article... https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/. If you check the commits area on the repo, your name is there but it doesn't look like it's linked to anything.

**Comment by hnrchrdl** [comment]
You are totally right, Git was not configured on my machine. Thx!

**Pull request merged**
